feeder/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'feeder.views.home', name='home'),
    # url(r'^feeder/', include('feeder.foo.urls')),

    url(r'^$', 'words.views.home'),
    url(r'^wordsets/$', 'words.views.frequent_wordsets'),
    url(r'^new_wordsets/$', 'words.views.new_wordsets'),
    url(r'^items/$', 'words.views.matching_items'),

    url(r'^scraper/$', 'scraper.views.scraper'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

feeder/scraper/models.py
from django.db import models

# Create your models here.

feeder/words/models.py
from django.db import models
from django.db import settings
from django.template.defaultfilters import truncatewords


class Item(models.Model):
    entry = models.ForeignKey('Entry')
    value = models.TextField()

    def truncated_value(self, arg=30):
        return truncatewords(self.value, arg)


class Entry(models.Model):
    feed = models.ForeignKey('Feed')
    pub_time = models.DateTimeField()

    class Meta:
        verbose_name_plural = 'entries'

    def __unicode__(self):
        return self.feed.url


class Feed(models.Model):
    url = models.URLField()

    def __unicode__(self):
        return self.url

feeder/scraper/views.py
import os
import json
from itertools import izip_longest
from subprocess import Popen, PIPE

from django.db import settings
from django.shortcuts import render_to_response


def scraper(request):
    def reshape(data):
        return {
            'columns': data.keys(),
            'rows': izip_longest(*data.values(), fillvalue='')
        }

    data = get_scrape_data()
    data = sorted(zip(data.keys(),
                      map(reshape, data.values())))

    return render_to_response(
        'scraper.html',
        {'data': data})


def get_scrape_data():
    scrape = os.path.join(settings.SITE_DIRECTORY,
                          'scraper/js/scrape.coffee')

    scraper = Popen(['coffee', scrape], stdin=PIPE, stdout=PIPE)
    scraper.stdin.close()

    return json.loads(scraper.stdout.read())

feeder/words/views.py
import operator
from datetime import datetime

from django.shortcuts import render_to_response
from django.db.models import Q
from django import forms
from django.template import RequestContext

from utils.time_utils import get_datetime_from_date_and_time
from utils.time_utils import datetime_at_start_of
from words.models import Item, Entry, Feed
from wordsets import get_frequent_wordsets, get_new_wordsets


def home(request):
    today = datetime.today()
    start_of_today = datetime_at_start_of(today)
    now = datetime.now()
    new_wordsets_form = NewWordsetsForm(
        initial={'new_wordsets_start_date': today,
                 'new_wordsets_start_time': start_of_today})

    if request.method == 'POST':
        wordsets_form = WordsetsForm(request.POST)
        if wordsets_form.is_valid():
            start_time = get_datetime_from_date_and_time(
                wordsets_form.cleaned_data['start_date'],
                wordsets_form.cleaned_data['start_time'])
            end_time = get_datetime_from_date_and_time(
                wordsets_form.cleaned_data['end_date'],
                wordsets_form.cleaned_data['end_time'])
            return frequent_wordsets(start_time, end_time)
    else:
        wordsets_form = WordsetsForm(initial={'start_date': today,
                                              'start_time': start_of_today,
                                              'end_date': today,
                                              'end_time': now})

    entry_pub_times = sorted(Entry.objects.values_list('pub_time', flat=True))
    earliest, latest = entry_pub_times[0], entry_pub_times[-1]
    n_entries = len(entry_pub_times)

    title = 'Feed Reader'
    n_items = Item.objects.count()
    n_feeds = Feed.objects.count()

    return render_to_response('browse.html', locals(),
                              context_instance=RequestContext(request))


class NewWordsetsForm(forms.Form):
    new_wordsets_start_date = forms.DateField(
        label='Start date',
        required=True,
        widget=forms.DateInput(
            attrs={
                'class': 'required, datepicker'}))
    new_wordsets_start_time = forms.TimeField(
        label='Start time',
        required=True,
        widget=forms.TimeInput(
            attrs={'class': 'required, timepicker'}))


class WordsetsForm(forms.Form):
    start_date = forms.DateField(
        label='Start date',
        required=True,
        widget=forms.DateInput(
            attrs={
                'class': 'required, datepicker'}))
    start_time = forms.TimeField(
        label='Start time',
        required=True,
        widget=forms.TimeInput(
            attrs={'class': 'required, timepicker'}))
    end_date = forms.DateField(
        label='End date',
        required=True,
        widget=forms.DateInput(
            attrs={
                'class': 'required, datepicker'}))
    end_time = forms.TimeField(
        required=True,
        widget=forms.TimeInput(
            attrs={'class': 'required, timepicker'}))


def new_wordsets(request):
    if request.method == 'POST':
        form = NewWordsetsForm(request.POST)
        if form.is_valid():
            start_time = get_datetime_from_date_and_time(
                form.cleaned_data['new_wordsets_start_date'],
                form.cleaned_data['new_wordsets_start_time'])
    else:
        raise Exception('Should not happen')

    items, wordsets = get_new_wordsets(start_time)
    n_items = Item.objects.count()

    return render_to_response('wordsets.html', locals())


def frequent_wordsets(start_time, end_time):
    items, wordsets = get_frequent_wordsets(start_time, end_time)
    n_items = Item.objects.count()

    return render_to_response('wordsets.html', locals())


def matching_items(request):
    wordset = request.GET['wordset'].split(',')

    item_Q = reduce(operator.and_,
                    (Q(value__contains=word) for word in wordset))
    items = Item.objects.filter(item_Q). \
            select_related('entry__feed'). \
            order_by('-entry__pub_time')

    return render_to_response('items.html', locals())

feeder/scraper/templates/scraper.html
<html>
  <head>
    <title>Scraper</title>
    <link rel='stylesheet' href='/static/css/scraper.css' type='text/css'/>
  </head>
  <body>
    {% for name, site_data in data %}
    <div class="site-data">
      <div class="site-title">{{ name }} </div>
    <table>
      <thead>
        {% for column in site_data.columns %}
        <td> {{ column }} </td>
        {% endfor %}
      </thead>
      <tbody>
        {% for row in site_data.rows %}
        <tr>
          {% for link in row %}
	  <td><a href={{ link.url }}>{{ link.text }}</a></td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
    {% endfor %}
  </body>
</html>

feeder/words/templates/base.html
<html>

  <head>

    {% block style %}
    <link rel='stylesheet' href='/static/js/jquery-ui.css' type='text/css'/>
    <link rel='stylesheet' href='/static/css/djangobook.css' type='text/css'/>
    <link rel='stylesheet' href='/static/css/feeder.css' type='text/css'/>
    {% endblock %}

    {% block js %}
    <script type='text/javascript' src='/static/js/jquery.js'></script>
    <script type='text/javascript' src='/static/js/jquery-ui.js'></script>
    <script type='text/javascript' src='/static/js/jquery.timePicker.js'></script>
    {% endblock %}

    <title>{{ title }}</title>

  </head>

  <body>
    <div id='bd'>
      {% block body %}
      {% endblock %}
    </div>
  </body>

</html>

feeder/words/templates/browse.html
{% extends "base.html" %}

{% block js %}
{{ block.super }}
<script type='text/javascript'>
  $(function() {
    $('#id_start_date').datepicker();
    $('#id_start_time').timePicker();
    $('#id_end_date').datepicker();
    $('#id_end_time').timePicker();
    $('#id_new_wordsets_start_date').datepicker();
    $('#id_new_wordsets_start_time').timePicker();
  });
</script>
{% endblock %}


{% block body %}

<h1>{{ title }}</h1>
<p>{{ now }}</p>
<br></br>
<p>Database contains {{ n_items }} <a href="/admin/words/item/">items</a> from {{ n_feeds }} <a href="/admin/words/feed/">feeds</a> ({{ earliest }} -- {{latest }})</p>
<h3>Frequent word clusters</h3>
<form action="/" method="post">{% csrf_token %}
{{ wordsets_form.as_p }}
<input type="submit" value="Go" />
</form>

<h3>New word clusters</h3>
<form action="/new_wordsets/" method="post">{% csrf_token %}
{{ new_wordsets_form.as_p }}
<input type="submit" value="Go" />
</form>

{% endblock %}

feeder/words/templates/items.html
<html>
<head></head>
<body>
  <table>
    <tbody>
      {% for item in items %}
      <tr>
	<td><a href={{ item.entry.feed.url }}>{{ item.entry.feed.url }}</a></td>
        <td>{{ item.entry.pub_time }}</td>
        <td>{{ item.value|truncatewords:30 }}</td>
      </tr>
      <tr></tr>
      {% endfor %}
    </tbody>
  </table>
</body>
</html>

feeder/words/templates/wordsets.html
<html>
<head></head>
<body>
  <h3> {{ start_time }} - {{ end_time }} ({{ items|length }} / {{ n_items }} items)</h3>
  <table>
    <tbody>
      {% for wordset, frequency in wordsets %}
      <tr>
	<td>{{ wordset|join:" " }}</td><td><a href="/items/?wordset={{ wordset|join:',' }}">{{ frequency }}</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</body>
</html>